### ISSUE TITLE
Change load khiva library

### ISSUE THREAD

**Issue by avilchess** [shapelets/khiva-java#31]
Currently, we are loading khiva from a given folder, thus our users are not free to install our library in the folder they want/can. This limitation is given by the following snippet of code in Library.java file.
```
    static {
        OS = System.getProperty("os.name").toLowerCase();
        if (OS.indexOf("mac") >= 0) {
            System.load("/usr/local/lib/libkhiva_jni.dylib");
        } else if (OS.indexOf("win") >= 0) {
            System.load("C:\\Program Files\\Khiva\\v0\\lib\\khiva_jni.dll");
        } else if (OS.indexOf("nix") >= 0 || OS.indexOf("nux") >= 0 || OS.indexOf("aix") > 0) {
            System.load("/usr/local/lib/libkhiva_jni.so");
        }
    }
```
To overcome this limitation, we should remove the full path, and let Java look for the library in ```System.getProperty("java.library.path")```. By default, it points to ```LD_LIBRARY_PATH```.

**Comment by raulbocanegra** [comment]
Fixed on #34
